version: '3'
services:
  cnil-pia-back:
    container_name: LINCnil-pia-back
    build: docker/cnil-pia-back
    restart: unless-stopped
    environment:
      - DATABASE_HOST=database
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=rootpostgres
      - SECRET_KEY_BASE=postgres
    depends_on:
      - database
    ports:
      - "3000:3000"
  cnil-pia-front:
    container_name: LINCnil-pia-front
    build: docker/cnil-pia-front
    restart: unless-stopped
    ports:
      - "8080:80"
  database:
    container_name: LINCnil-pia-db
    image: postgres:10.3
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=rootpostgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
